### ISSUE TITLE
Some related videos thumbnails stay "blank" [Waterfox Classic]

### ISSUE THREAD

**Issue by decembre** [pietervanheijningen/clickbait-remover-for-youtube#54]
Have you noticed that some related videos thumbnails stay blank?
If i select option "No Change" , it's ok.

Browser:
Waterfox Classic

Test link:
https://www.youtube.com/watch?v=NTrm_idbhUk

Note:
A screenshot:
![PB - YOUTUBE - NO THUMBNAIL - 2023-01-28_165728](https://user-images.githubusercontent.com/868778/215318087-024ca043-d301-4c06-bdac-dc841044a133.jpg)

Was after a question here:
<a href="https://greasyfork.org/fr/scripts/428651-tabview-youtube/discussions/156915#comment-360902">[have you noticed that some related videos thumbnails stay blank?](https://greasyfork.org/fr/scripts/428651-tabview-youtube/discussions/156915#comment-360902)</a>

**Comment by cyfung1031** [comment]
If you just don't want to animated overlay, just set them `display: none`
For video title, it is just a css rule.

You don't have to bother with this extension.
You can create [UserCSS with Stylus](https://github.com/openstyles/stylus/wiki/Writing-UserCSS) to make them toggleable.

```css
ytd-thumbnail #mouseover-overlay, ytd-thumbnail #hover-overlays {
    display: none;
}

#related #video-title {
    text-transform: lowercase;
}
```
